from __future__ import annotations

from typing import Protocol, Sequence, Optional
from app.core.models import UserIdentity, UserStats, TopRow, ChatState, CircleMessage


class Repository(Protocol):
    # --- chat state ---
    def ensure_chat_state(self, *, chat_id: int) -> None: ...
    def get_chat_state(self, *, chat_id: int) -> ChatState: ...
    def set_last_circle_ts(self, *, chat_id: int, ts: int) -> None: ...
    def set_last_rating_ts(self, *, chat_id: int, ts: int) -> None: ...
    def list_active_chats(self) -> Sequence[int]: ...
    def set_ratings_enabled(self, *, chat_id: int, enabled: bool) -> None: ...

    # --- users ---
    def upsert_user(self, identity: UserIdentity) -> None: ...
    def get_user_stats(self, *, chat_id: int, user_id: int) -> Optional[UserStats]: ...
    def add_circle_points(self, *, chat_id: int, user_id: int, points: int) -> None: ...
    def add_reaction_points(self, *, chat_id: int, user_id: int, points: int) -> None: ...

    # --- circles ---
    def insert_circle_message(self, circle: CircleMessage) -> bool: ...
    def try_get_circle_author_id(self, *, chat_id: int, message_id: int) -> Optional[int]: ...

    # --- reactions log (idempotency) ---
    def try_insert_reaction(self, *, chat_id: int, message_id: int, reactor_id: int, emoji: str) -> bool: ...
    def try_delete_reaction(self, *, chat_id: int, message_id: int, reactor_id: int, emoji: str) -> bool: ...

    # --- leaderboards ---
    def get_top(self, *, chat_id: int, limit: int) -> Sequence[TopRow]: ...
    def get_zero_users(self, *, chat_id: int, criteria: str, limit: int) -> Sequence[UserStats]: ...
